# -*- coding: utf-8 -*-
"""deep_learning_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U4SlPv9Y6NtMyFqqW8rFX1cT0CAwkhc2

# Brain Tumor MRI Classification using Deep Learning (CNN)

This notebook demonstrates the complete workflow for building a Convolutional Neural Network (CNN) to classify brain MRI images into four tumor categories.

The notebook includes:

- Imports
- Dataset loading
- Helper Functions
- Data exploration
- Data Quailty Assessment
- Data preprocessing
- Data augmentation
- CNN model development
- Model training
- Performance evaluation

# Imports
"""

# Standard Libraries
import os
import random
import warnings
import zipfile
from collections import defaultdict
from google.colab import files

# Data Manipulation
import numpy as np
import pandas as pd

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Image Processing
from PIL import Image

# Scikit-Learn
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix
)

# TensorFlow / Keras
import tensorflow as tf
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Dense,
    Flatten,
    Dropout,
    BatchNormalization
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator

"""# Dataset Loading

In this section we upload the dataset into Google Colab and extract it so it can be accessed during the project.
"""

uploaded = files.upload()

!unzip archive.zip -d dataset

!ls dataset

"""# Helper Functions

To improve the organization and readability of the notebook, reusable helper functions are defined before they are used.

## Create Dataset DataFrame

The MRI images are organized into folders, where each folder represents a different class.

The following function scans the dataset directory, reads every image file, and creates a **Pandas DataFrame** containing:

- **File Path:** The complete path to each image.
- **Label:** The class name extracted from the parent folder.
"""

def create_dataframe_from_paths(base_dir):
    classes = []
    class_paths = []

    for class_name in os.listdir(base_dir):
        class_path_full = os.path.join(base_dir, class_name)
        if os.path.isdir(class_path_full):
            for img_name in os.listdir(class_path_full):
                if img_name.endswith(('.jpg', '.jpeg', '.png')):
                    classes.append(class_name)
                    class_paths.append(os.path.join(class_path_full, img_name))

    df = pd.DataFrame({'Class Path': class_paths, 'Class': classes})
    return df

"""## Generate Dataset Information

Before training the model, it is useful to understand the composition of the dataset.

The following function summarizes important information such as:

- Total number of images.
- Number of images in each class.
- Class distribution.
"""

def get_dataset_info(base_dir):
    total_images = 0
    class_counts = defaultdict(int)
    all_image_paths = []

    for class_name in os.listdir(base_dir):
        class_path = os.path.join(base_dir, class_name)
        if os.path.isdir(class_path):
            for img_name in os.listdir(class_path):
                if img_name.endswith(('.jpg', '.jpeg', '.png')):
                    all_image_paths.append(os.path.join(class_path, img_name))
                    class_counts[class_name] += 1
                    total_images += 1
    return total_images, class_counts, all_image_paths

"""# Dataset Exploration

In this section, the training and testing directories are specified, and the helper functions are used to load the image paths and labels into Pandas DataFrames. The dataset is then inspected to verify that the images have been loaded correctly and to obtain summary statistics about each class.

## Define Dataset Paths
"""

train_dir = 'dataset/Training'
test_dir = 'dataset/Testing'

"""## Load the Dataset

The helper function `create_dataframe_from_paths()` is used to scan the dataset directories and create two DataFrames:

- **Training DataFrame (`train_df`)**
- **Testing DataFrame (`test_df`)**

Each DataFrame contains the image file path and its corresponding class label, providing a structured representation of the dataset that simplifies further analysis and preprocessing.
"""

train_df = create_dataframe_from_paths(train_dir)
test_df = create_dataframe_from_paths(test_dir)

train_df

test_df

"""## Dataset Statistics & Visualization

### Statictics

#### Training DataSet
"""

train_total_images, train_class_counts, train_image_paths = get_dataset_info(train_dir)
print(f"Total training images: {train_total_images}")
print(f"Number of training classes: {len(train_class_counts)}")
print("Images per training class:")
for class_name, count in sorted(train_class_counts.items()):
    print(f"  {class_name}: {count} images")

class_counts = train_df['Class'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(class_counts, labels=class_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Classes in Training Data')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

plt.figure(figsize=(15,7))
ax = sns.countplot(data=train_df , y=train_df['Class'])

plt.xlabel('')
plt.ylabel('')
plt.title('Count of images in each class', fontsize=20)
ax.bar_label(ax.containers[0])
plt.show()

"""#### Test Data Set"""

test_total_images, test_class_counts, test_image_paths = get_dataset_info(test_dir)
print(f"Total testing images: {test_total_images}")
print(f"Number of testing classes: {len(test_class_counts)}")
print("Images per testing class:")
for class_name, count in sorted(test_class_counts.items()):
    print(f"  {class_name}: {count} images")

class_counts = test_df['Class'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(class_counts, labels=class_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribution of Classes in Training Data')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

plt.figure(figsize=(15,7))
ax = sns.countplot(data=test_df , y=test_df['Class'])

plt.xlabel('')
plt.ylabel('')
plt.title('Count of images in each class', fontsize=20)
ax.bar_label(ax.containers[0])
plt.show()

"""### Visualization

#### Training Data
"""

# This sample_train_df will be used as the specific set of raw images for comparison
# with ImageDataGenerator output.
sample_train_df = train_df.sample(n=16, random_state=42)

plt.figure(figsize=(12, 12)) # Adjusted figure size for a 4x4 grid
for i, row in enumerate(sample_train_df.iterrows()):
    img_path = row[1]['Class Path']
    img_class = row[1]['Class']

    img = Image.open(img_path)

    plt.subplot(4, 4, i + 1) # Changed to 4 rows and 4 columns
    plt.imshow(img)
    plt.title(f'Class: {img_class}')
    plt.axis('off')

plt.tight_layout()
plt.show()

"""#### Test Data"""

sample_test_df = test_df.sample(n=16, random_state=42)

plt.figure(figsize=(12, 12))
for i, row in enumerate(sample_test_df.iterrows()):
    img_path = row[1]['Class Path']
    img_class = row[1]['Class']

    img = Image.open(img_path)

    plt.subplot(4, 4, i + 1)
    plt.imshow(img)
    plt.title(f'Class: {img_class}')
    plt.axis('off')

plt.tight_layout()
plt.show()

"""# Data Quality Assessment

Before preprocessing the dataset, it is important to verify its quality and consistency.

## Checking Nulls
"""

print("Null values in training data:")
print(train_df.isnull().sum())
print("\nNull values in testing data:")
print(test_df.isnull().sum())

"""## Checking The Duplication"""

print("Duplicate rows in training data:")
print(train_df.duplicated().sum())
print("\nDuplicate rows in testing data:")
print(test_df.duplicated().sum())

"""# Data Preprocessing

In this section, we prepare the dataset by creating a validation set, defining the image dimensions and batch size, applying image preprocessing and data augmentation techniques, and creating data generators for training, validation, and testing.

## Create Training and Validation Sets

The original training dataset is divided into two subsets:

- **Training Set:** Used to train the CNN by updating the model's weights.
- **Validation Set:** Used during training to evaluate the model's performance on unseen data and monitor overfitting.
"""

train_df, valid_df = train_test_split(
    train_df,
    test_size=0.15,
    stratify=train_df["Class"],
    random_state=42
)

print(f"New Training images : {len(train_df)}")
print(f"Validation images   : {len(valid_df)}")
print(f"Test images         : {len(test_df)}")

"""## Image Preprocessing and Data Augmentation

The `ImageDataGenerator` is used to prepare the images before they are passed to the CNN.

For the **training dataset**, data augmentation is applied by introducing random transformations such as rotations, shifts, zooming, and horizontal flipping. These transformations generate new variations of the existing images, increasing the diversity of the training data without collecting additional MRI scans.

In addition, pixel values are normalized by scaling them to the range **0–1**, allowing the CNN to train more efficiently.

For the **validation** and **testing** datasets, only normalization is applied so that the model is evaluated using the original images without artificial modifications.
"""

batch_size = 32
img_size = (299, 299)

_gen = ImageDataGenerator(rescale=1/255,
                          brightness_range=(0.8, 1.2))

ts_gen = ImageDataGenerator(rescale=1/255)


tr_gen = _gen.flow_from_dataframe(train_df, x_col='Class Path',
                                  y_col='Class', batch_size=batch_size,
                                  target_size=img_size)

valid_gen = _gen.flow_from_dataframe(valid_df, x_col='Class Path',
                                     y_col='Class', batch_size=batch_size,
                                     target_size=img_size)

ts_gen = ts_gen.flow_from_dataframe(test_df, x_col='Class Path',
                                  y_col='Class', batch_size=16,
                                  target_size=img_size, shuffle=False)

"""### Before Standridizing"""

sample_train_df = train_df.sample(n=16, random_state=42)

plt.figure(figsize=(12, 12))
for i, row in enumerate(sample_train_df.iterrows()):
    img_path = row[1]['Class Path']
    img_class = row[1]['Class']

    img = Image.open(img_path)

    plt.subplot(4, 4, i + 1)
    plt.imshow(img)
    plt.title(f'Class: {img_class}')
    plt.axis('off')

plt.tight_layout()
plt.show()

"""### After Standradizing"""

import numpy as np

# Get a batch of augmented images and labels from the training generator
images, labels = next(tr_gen)

# Get class names from the generator's class_indices
class_dict = tr_gen.class_indices
classes = list(class_dict.keys())

plt.figure(figsize=(12, 12)) # Adjusted figure size for a 4x4 grid

for i in range(16): # Plotting 16 images in a 4x4 grid
    plt.subplot(4, 4, i + 1)
    plt.imshow(images[i])

    # Determine the class name from the one-hot encoded label
    class_name = classes[np.argmax(labels[i])]
    plt.title(f'Class: {class_name}')
    plt.axis('off')

plt.tight_layout()
plt.show()

"""# CNN Model Architecture

A **Convolutional Neural Network (CNN)** is designed specifically for image classification tasks. Unlike traditional machine learning algorithms, CNNs automatically learn important features directly from images, such as edges, shapes, textures, and complex patterns.

In this project, a custom CNN architecture is developed to classify brain MRI images into four categories. The model consists of convolutional layers for feature extraction, pooling layers for dimensionality reduction, normalization and dropout layers to improve generalization, and fully connected layers for final classification.

## Build the CNN Model

The following code defines the architecture of the Convolutional Neural Network.

The model is built sequentially, where each layer performs a specific task:

- **Convolutional Layers (Conv2D):** Extract visual features from the MRI images.
- **Batch Normalization:** Stabilizes and accelerates the learning process.
- **Max Pooling Layers:** Reduce the spatial dimensions while preserving important features.
- **Dropout Layers:** Randomly deactivate neurons during training to reduce overfitting.
- **Dense Layers:** Combine the extracted features to perform classification.
- **Output Layer:** Produces the probability for each brain tumor class using the Softmax activation function.
"""

num_classes = len(tr_gen.class_indices);

input_shape = img_size + (3,)

model = Sequential([
    Input(shape=input_shape), # Explicitly define the input layer
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'), # Restored this layer
    MaxPooling2D((2, 2)), # Restored this layer
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

"""## Compile the Model

After defining the network architecture, the model is compiled.

During compilation, three important components are specified:

- **Optimizer:** Determines how the model updates its weights during training.
- **Loss Function:** Measures the difference between the predicted and actual class labels.
- **Evaluation Metric:** Tracks the model's performance during training and validation.
"""

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

"""## Model Summary

The model summary provides an overview of the network architecture, including the output shape of each layer and the number of trainable parameters.
"""

model.summary()

"""# Model Training

After defining and compiling the CNN architecture, the model is trained using the prepared training dataset.

## Train the CNN Model

The `model.fit()` function starts the training process by repeatedly passing batches of images through the network.

During each epoch, the following steps are performed:

1. A batch of training images is processed.
2. Predictions are generated.
3. The loss is calculated by comparing the predictions with the true labels.
4. The optimizer updates the model's weights to reduce the prediction error.
5. The model is evaluated using the validation dataset to monitor its performance on unseen data.
"""

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(tr_gen,
                      epochs=50,
                      validation_data=valid_gen,
                      callbacks=[early_stopping])

"""## Training Results

After the training process is completed, the recorded history contains valuable information about the model's learning progress throughout all epochs.
"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(12, 5))

# Plot training & validation accuracy values
plt.subplot(1, 2, 1) # 1 row, 2 columns, first plot
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

# Plot training & validation loss values
plt.subplot(1, 2, 2) # 1 row, 2 columns, second plot
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')

plt.tight_layout()
plt.show()

"""# Model Evaluation

Once the training process is complete, the model's performance must be evaluated to determine how well it generalizes to new, unseen MRI images.

## Evaluate Model Performance

The trained model is evaluated on the training, validation, and testing datasets using the `evaluate()` function.

This provides the **loss** and **accuracy** for each dataset, allowing us to compare the model's performance during training with its ability to generalize to unseen data.
"""

train_score = model.evaluate(tr_gen, verbose=1)
valid_score = model.evaluate(valid_gen, verbose=1)
test_score = model.evaluate(ts_gen, verbose=1)

print(f"Train Loss: {train_score[0]:.4f}")
print(f"Train Accuracy: {train_score[1]*100:.2f}%")
print('-' * 20)
print(f"Validation Loss: {valid_score[0]:.4f}")
print(f"Validation Accuracy: {valid_score[1]*100:.2f}%")
print('-' * 20)
print(f"Test Loss: {test_score[0]:.4f}")
print(f"Test Accuracy: {test_score[1]*100:.2f}%")

"""## Confusion Matrix

The confusion matrix provides a detailed breakdown of the model's predictions by comparing the predicted class with the actual class.

"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

# Get true labels from the test generator
y_true = ts_gen.labels

# Get predictions from the model
predictions = model.predict(ts_gen)

# Convert predictions to class labels (index of the highest probability)
y_pred = np.argmax(predictions, axis=1)

# Get class names in the order of their assigned integer labels by the generator
class_names = [name for name, idx in sorted(ts_gen.class_indices.items(), key=lambda item: item[1])]

# Generate the confusion matrix
cm = confusion_matrix(y_true, y_pred)

# Plot the confusion matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""## Generate Predictions

After evaluating the model, predictions are generated for the testing dataset.

For each MRI image, the CNN produces a probability for every class. The class with the highest probability is selected as the model's final prediction.

These predictions are then compared with the true labels to calculate additional evaluation metrics.
"""

import numpy as np

# Get predictions from the model on the test data
predictions = model.predict(ts_gen)

# Convert predictions (probabilities) to class labels
y_pred = np.argmax(predictions, axis=1)

print("Raw predictions (probabilities for each class):")
print(predictions)
print("\nPredicted class labels:")
print(y_pred)

"""## Classification Report

The classification report summarizes the model's performance using several important evaluation metrics:

- **Precision:** Measures how many predicted samples of a class are actually correct.
- **Recall:** Measures how many actual samples of a class were correctly identified.
- **F1-Score:** The harmonic mean of precision and recall.
- **Support:** The number of true samples belonging to each class.
"""

print(classification_report(y_true, y_pred, target_names=class_names))

# Download it directly to your computer
files.download('deep_learning_model.keras')

