# -*- coding: utf-8 -*-
"""HF_Model_ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnOksdUe35wizdn1w1RnHkxTxQp7lqEd

# Imports
"""

import os
import numpy as np
import pandas as pd
import warnings
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import hashlib
import matplotlib
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import recall_score
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report, accuracy_score

"""# File Upload"""

HF_Data = pd.read_csv('/content/heart.csv')

"""# Data exploration"""

display(HF_Data)

HF_Data.info()

HF_Data.describe()

# Some graphs to present the data

sns.set_style("whitegrid")

plt.figure(figsize=(15, 10))

plt.subplot(2, 2, 1)
sns.countplot(x='HeartDisease', data=HF_Data)
plt.title('Distribution of Heart Disease')

plt.subplot(2, 2, 2)
sns.histplot(HF_Data['Age'], kde=True)
plt.title('Distribution of Age')

plt.subplot(2, 2, 3)
sns.countplot(x='Sex', hue='HeartDisease', data=HF_Data)
plt.title('Heart Disease by Sex')

plt.subplot(2, 2, 4)
sns.boxplot(x='HeartDisease', y='Age', data=HF_Data)
plt.title('Age Distribution by Heart Disease')

plt.tight_layout()
plt.show()

"""# Preprocessing (null-values/duplicates)

**1) Drop Duplicaes**
"""

HF_Data.duplicated().sum()

HF_Data.drop_duplicates(inplace=True)

HF_Data.duplicated().sum()

"""**2) Fixing null-values**"""

HF_Data.isnull().sum()

# Replace nulls in CPT with the mode (Most common)
cpt_mode = HF_Data['ChestPainType'].mode()[0]
HF_Data['ChestPainType'] = HF_Data['ChestPainType'].fillna(cpt_mode)

# Replace nulls in MaxHR with the mean (AVG)
max_hr_mean = HF_Data['MaxHR'].mean()
HF_Data['MaxHR'] = HF_Data['MaxHR'].fillna(max_hr_mean)

HF_Data.isnull().sum()

"""# preprocessing (Encoding)"""

HF_Data.head(2)

# One-hot encode (sex & excricise angina)
columns_to_encode = ['Sex', 'ExerciseAngina']
HF_Data = pd.get_dummies(HF_Data, columns=columns_to_encode, drop_first=True)

# Label encode (CPT, Resting ECG & ST_slope)
le = LabelEncoder()
cols_to_label_encode = ['ChestPainType', 'RestingECG', 'ST_Slope']
for col in cols_to_label_encode:
    HF_Data[col] = le.fit_transform(HF_Data[col])

HF_Data.head()

"""# preprocessing (IQR/corr matrix)

**1) IQR**
"""

# Generate Box plot
plt.figure(figsize=(20, 10))
sns.boxplot(data=HF_Data)
plt.title('Box Plots for All Features')
plt.xticks(rotation=45)
plt.show()

# Replace all 0 values in CHOL with the mean (BEC. 0 means no data = null)
    # 0 CHOL in not Biologicaly possible
chol_mean = HF_Data[HF_Data['Cholesterol'] != 0]['Cholesterol'].mean()
HF_Data['Cholesterol'] = HF_Data['Cholesterol'].replace(0, chol_mean)

# Replace all 0 values in RestingBP with the mean
rbp_mean = HF_Data[HF_Data['RestingBP'] != 0]['RestingBP'].mean()
HF_Data['RestingBP'] = HF_Data['RestingBP'].replace(0, rbp_mean)

# Generate Box plot after cleaning
plt.figure(figsize=(20, 10))
sns.boxplot(data=HF_Data)
plt.title('Box Plots for All Features (After Cleaning)')
plt.xticks(rotation=45)
plt.show()

"""**2) corr matrix**"""

# Calculate the correlation matrix
corr_matrix = HF_Data.corr()
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)
plt.title('Correlation Matrix Heatmap')
plt.show()

# Calculate correlation with the target variable 'HeartDisease' specifically
target_corr = HF_Data.corr()[['HeartDisease']].sort_values(by='HeartDisease', ascending=False)
plt.figure(figsize=(6, 8))
sns.heatmap(target_corr, annot=True, cmap='coolwarm', fmt='.3f')
plt.title('Correlation of Features with HeartDisease')
plt.show()

# Drop RestingECG column
HF_Data = HF_Data.drop(columns=['RestingECG'])

"""# Dividing (test/train)"""

X = HF_Data.drop('HeartDisease', axis=1)
y = HF_Data['HeartDisease']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Visualize the train/test split sizes
split_counts = pd.Series({'Train': len(X_train), 'Test': len(X_test)})

plt.figure(figsize=(8, 6))
split_counts.plot(kind='bar', color=['skyblue', 'salmon'])
plt.title('Train vs Test Split Size')
plt.ylabel('Number of Samples')
plt.xticks(rotation=0)
for i, val in enumerate(split_counts):
    plt.text(i, val + 5, str(val), ha='center', fontweight='bold')

plt.show()

"""# Scaling"""

scaler = MinMaxScaler()
X_train = pd.DataFrame(scaler.fit_transform(X_train), columns=X_train.columns, index=X_train.index)
X_test = pd.DataFrame(scaler.transform(X_test), columns=X_test.columns, index=X_test.index)

# Setting up the figure layout
plt.figure(figsize=(20, 12))

# 1. Distribution of Cholesterol by Heart Disease
plt.subplot(2, 2, 1)
sns.kdeplot(data=HF_Data, x='Cholesterol', hue='HeartDisease', fill=True, palette='viridis')
plt.title('Cholesterol Distribution by Heart Disease Status')

# 2. MaxHR vs Age with Heart Disease Hue
plt.subplot(2, 2, 2)
sns.scatterplot(data=HF_Data, x='Age', y='MaxHR', hue='HeartDisease', palette='magma', alpha=0.7)
plt.title('Max Heart Rate vs Age')

# 3. Heart Disease count by ST Slope
plt.subplot(2, 2, 3)
sns.countplot(data=HF_Data, x='ST_Slope', hue='HeartDisease', palette='Set2')
plt.title('Heart Disease Frequency for ST Slope Types')

# 4. Boxplot of Oldpeak
plt.subplot(2, 2, 4)
sns.boxplot(data=HF_Data, x='HeartDisease', y='Oldpeak', hue='HeartDisease', palette='pastel', legend=False)
plt.title('ST Depression (Oldpeak) by Heart Disease Status')

plt.tight_layout()
plt.show()

"""# Model training phase

**1) Logistic regression**
"""

model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

print(f"Test Accuracy (Standard Split): {accuracy * 100:.2f}%")
print(f"Test Recall (Standard Split): {recall * 100:.2f}%")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

log_reg = LogisticRegression(max_iter=10000)
n_splits = 5
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
fold = 1
accuracies = []
recalls = []

for train_index, val_index in skf.split(X_train, y_train):
    X_fold_train, X_fold_val = X_train.iloc[train_index], X_train.iloc[val_index]
    y_fold_train, y_fold_val = y_train.iloc[train_index], y_train.iloc[val_index]

    log_reg.fit(X_fold_train, y_fold_train)
    y_pred_fold = log_reg.predict(X_fold_val)

    acc = accuracy_score(y_fold_val, y_pred_fold)
    rec = recall_score(y_fold_val, y_pred_fold)

    accuracies.append(acc)
    recalls.append(rec)

    print(f"--- Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"Average Stratified K-Fold Accuracy: {np.mean(accuracies) * 100:.2f}%")
print(f"Average Stratified K-Fold Recall: {np.mean(recalls) * 100:.2f}%")

"""**2) SVM**"""

svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

svm_accuracy = accuracy_score(y_test, y_pred_svm)
svm_recall = recall_score(y_test, y_pred_svm)

print(f"SVM Test Accuracy: {svm_accuracy * 100:.2f}%")
print(f"SVM Test Recall: {svm_recall * 100:.2f}%")
print("\nSVM Classification Report:")
print(classification_report(y_test, y_pred_svm))

svm_cv = SVC(kernel='linear', random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

svm_accuracies = []
svm_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    svm_cv.fit(X_f_train, y_f_train)
    y_f_pred = svm_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    svm_accuracies.append(acc)
    svm_recalls.append(rec)

    print(f"--- SVM Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage SVM Stratified K-Fold Accuracy: {np.mean(svm_accuracies) * 100:.2f}%")
print(f"Average SVM Stratified K-Fold Recall: {np.mean(svm_recalls) * 100:.2f}%")

"""**3) Decision tree**"""

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)
dt_recall = recall_score(y_test, y_pred_dt)

print(f"Decision Tree Test Accuracy: {dt_accuracy * 100:.2f}%")
print(f"Decision Tree Test Recall: {dt_recall * 100:.2f}%")
print("\nDecision Tree Classification Report:")
print(classification_report(y_test, y_pred_dt))

dt_cv = DecisionTreeClassifier(random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

dt_accuracies = []
dt_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    dt_cv.fit(X_f_train, y_f_train)
    y_f_pred = dt_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    dt_accuracies.append(acc)
    dt_recalls.append(rec)

    print(f"--- DT Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage DT Stratified K-Fold Accuracy: {np.mean(dt_accuracies) * 100:.2f}%")
print(f"Average DT Stratified K-Fold Recall: {np.mean(dt_recalls) * 100:.2f}%")

"""**4) Random forest**"""

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_recall = recall_score(y_test, y_pred_rf)

print(f"Random Forest Test Accuracy: {rf_accuracy * 100:.2f}%")
print(f"Random Forest Test Recall: {rf_recall * 100:.2f}%")
print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

rf_cv = RandomForestClassifier(random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

rf_accuracies = []
rf_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    rf_cv.fit(X_f_train, y_f_train)
    y_f_pred = rf_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    rf_accuracies.append(acc)
    rf_recalls.append(rec)

    print(f"--- RF Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage Random Forest Stratified K-Fold Accuracy: {np.mean(rf_accuracies) * 100:.2f}%")
print(f"Average Random Forest Stratified K-Fold Recall: {np.mean(rf_recalls) * 100:.2f}%")

"""**5) GR boost**"""

gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(X_train, y_train)

y_pred_gb = gb_model.predict(X_test)

gb_accuracy = accuracy_score(y_test, y_pred_gb)
gb_recall = recall_score(y_test, y_pred_gb)

print(f"Gradient Boosting Test Accuracy: {gb_accuracy * 100:.2f}%")
print(f"Gradient Boosting Test Recall: {gb_recall * 100:.2f}%")
print("\nGradient Boosting Classification Report:")
print(classification_report(y_test, y_pred_gb))

gb_cv = GradientBoostingClassifier(random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

gb_accuracies = []
gb_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    gb_cv.fit(X_f_train, y_f_train)
    y_f_pred = gb_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    gb_accuracies.append(acc)
    gb_recalls.append(rec)

    print(f"--- GB Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage Gradient Boosting Stratified K-Fold Accuracy: {np.mean(gb_accuracies) * 100:.2f}%")
print(f"Average Gradient Boosting Stratified K-Fold Recall: {np.mean(gb_recalls) * 100:.2f}%")

"""**6) KNN**"""

knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

knn_accuracy = accuracy_score(y_test, y_pred_knn)
knn_recall = recall_score(y_test, y_pred_knn)

print(f"KNN Test Accuracy: {knn_accuracy * 100:.2f}%")
print(f"KNN Test Recall: {knn_recall * 100:.2f}%")
print("\nKNN Classification Report:")
print(classification_report(y_test, y_pred_knn))

knn_cv = KNeighborsClassifier()
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

knn_accuracies = []
knn_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    knn_cv.fit(X_f_train, y_f_train)
    y_f_pred = knn_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    knn_accuracies.append(acc)
    knn_recalls.append(rec)

    print(f"--- KNN Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage KNN Stratified K-Fold Accuracy: {np.mean(knn_accuracies) * 100:.2f}%")
print(f"Average KNN Stratified K-Fold Recall: {np.mean(knn_recalls) * 100:.2f}%")

"""**7) XG boost**"""

xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

xgb_accuracy = accuracy_score(y_test, y_pred_xgb)
xgb_recall = recall_score(y_test, y_pred_xgb)

print(f"XGBoost Test Accuracy: {xgb_accuracy * 100:.2f}%")
print(f"XGBoost Test Recall: {xgb_recall * 100:.2f}%")
print("\nXGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgb))

xgb_cv = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

xgb_accuracies = []
xgb_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    xgb_cv.fit(X_f_train, y_f_train)
    y_f_pred = xgb_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    xgb_accuracies.append(acc)
    xgb_recalls.append(rec)

    print(f"--- XGBoost Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage XGBoost Stratified K-Fold Accuracy: {np.mean(xgb_accuracies) * 100:.2f}%")
print(f"Average XGBoost Stratified K-Fold Recall: {np.mean(xgb_recalls) * 100:.2f}%")

"""**8) Nayve bayesd**"""

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)

nb_accuracy = accuracy_score(y_test, y_pred_nb)
nb_recall = recall_score(y_test, y_pred_nb)

print(f"Naive Bayes Test Accuracy: {nb_accuracy * 100:.2f}%")
print(f"Naive Bayes Test Recall: {nb_recall * 100:.2f}%")
print("\nNaive Bayes Classification Report:")
print(classification_report(y_test, y_pred_nb))

nb_cv = GaussianNB()
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

nb_accuracies = []
nb_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    nb_cv.fit(X_f_train, y_f_train)
    y_f_pred = nb_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    nb_accuracies.append(acc)
    nb_recalls.append(rec)

    print(f"--- Naive Bayes Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage Naive Bayes Stratified K-Fold Accuracy: {np.mean(nb_accuracies) * 100:.2f}%")
print(f"Average Naive Bayes Stratified K-Fold Recall: {np.mean(nb_recalls) * 100:.2f}%")

"""**9) Bagging**"""

bag_model = BaggingClassifier(random_state=42)
bag_model.fit(X_train, y_train)

y_pred_bag = bag_model.predict(X_test)

bag_accuracy = accuracy_score(y_test, y_pred_bag)
bag_recall = recall_score(y_test, y_pred_bag)

print(f"Bagging Test Accuracy: {bag_accuracy * 100:.2f}%")
print(f"Bagging Test Recall: {bag_recall * 100:.2f}%")
print("\nBagging Classification Report:")
print(classification_report(y_test, y_pred_bag))

bag_cv = BaggingClassifier(random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

bag_accuracies = []
bag_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    bag_cv.fit(X_f_train, y_f_train)
    y_f_pred = bag_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    bag_accuracies.append(acc)
    bag_recalls.append(rec)

    print(f"--- Bagging Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage Bagging Stratified K-Fold Accuracy: {np.mean(bag_accuracies) * 100:.2f}%")
print(f"Average Bagging Stratified K-Fold Recall: {np.mean(bag_recalls) * 100:.2f}%")

"""**10) SVC**"""

svc_rbf = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)

svc_rbf.fit(X_train, y_train)
y_pred_svc = svc_rbf.predict(X_test)

svc_acc = accuracy_score(y_test, y_pred_svc)
svc_rec = recall_score(y_test, y_pred_svc)

print(f"SVC (RBF) Test Accuracy: {svc_acc * 100:.2f}%")
print(f"SVC (RBF) Test Recall: {svc_rec * 100:.2f}%")
print("\nSVC (RBF) Classification Report:")
print(classification_report(y_test, y_pred_svc))

svc_cv = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

svc_accuracies = []
svc_recalls = []
fold = 1

for train_idx, val_idx in skf.split(X_train, y_train):
    X_f_train, X_f_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
    y_f_train, y_f_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

    svc_cv.fit(X_f_train, y_f_train)
    y_f_pred = svc_cv.predict(X_f_val)

    acc = accuracy_score(y_f_val, y_f_pred)
    rec = recall_score(y_f_val, y_f_pred)

    svc_accuracies.append(acc)
    svc_recalls.append(rec)

    print(f"--- SVC Fold {fold} ---")
    print(f"Accuracy: {acc * 100:.2f}%")
    print(f"Recall: {rec * 100:.2f}%")
    fold += 1

print(f"\nAverage SVC (RBF) Stratified K-Fold Accuracy: {np.mean(svc_accuracies) * 100:.2f}%")
print(f"Average SVC (RBF) Stratified K-Fold Recall: {np.mean(svc_recalls) * 100:.2f}%")

"""# Algorithm comapring"""

models = ['LogReg', 'SVM (Linear)', 'SVC (RBF)', 'DT', 'RF', 'GB', 'KNN', 'XGB', 'NB', 'Bagging']

# Updated to match the 10 models above by removing the 6th element (Tuned RF metrics)
avg_accuracies = [
    np.mean(accuracies), np.mean(svm_accuracies), np.mean(svc_accuracies),
    np.mean(dt_accuracies), np.mean(rf_accuracies),
    np.mean(gb_accuracies), np.mean(knn_accuracies), np.mean(xgb_accuracies),
    np.mean(nb_accuracies), np.mean(bag_accuracies)
]

avg_recalls = [
    np.mean(recalls), np.mean(svm_recalls), np.mean(svc_recalls),
    np.mean(dt_recalls), np.mean(rf_recalls),
    np.mean(gb_accuracies), np.mean(knn_accuracies), np.mean(xgb_accuracies),
    np.mean(nb_accuracies), np.mean(bag_accuracies)
]

# Plotting
x = np.arange(len(models))
width = 0.35

fig, ax = plt.subplots(figsize=(14, 6))
rects1 = ax.bar(x - width/2, [a * 100 for a in avg_accuracies], width, label='Accuracy', color='skyblue')
rects2 = ax.bar(x + width/2, [r * 100 for r in avg_recalls], width, label='Recall', color='salmon')

ax.set_ylabel('Score (%)')
ax.set_title('Average K-Fold Performance')
ax.set_xticks(x)
ax.set_xticklabels(models, rotation=45)
ax.legend()

plt.ylim(60, 100)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 1. Create a master dataframe excluding the Voting Ensemble
master_df = pd.DataFrame({
    'Model': models,
    'Accuracy (%)': [a * 100 for a in avg_accuracies],
    'Recall (%)': [r * 100 for r in avg_recalls]
})

# Table 1: Accuracy Focus
accuracy_table = master_df[['Model', 'Accuracy (%)']].sort_values(by='Accuracy (%)', ascending=False).reset_index(drop=True)
print("Table 1: Model Accuracy")
display(accuracy_table.style.background_gradient(cmap='Greens'))

# Table 2: Recall Focus
recall_table = master_df[['Model', 'Recall (%)']].sort_values(by='Recall (%)', ascending=False).reset_index(drop=True)
print("\nTable 2: Model Recall")
display(recall_table.style.background_gradient(cmap='Oranges'))

# Plotting the results (Individual Models Only)
plt.figure(figsize=(16, 8))

x_axis = np.arange(len(models))

plt.bar(x_axis - 0.2, master_df['Accuracy (%)'], 0.4, label='Accuracy', color='#2ecc71', edgecolor='black')
plt.bar(x_axis + 0.2, master_df['Recall (%)'], 0.4, label='Recall', color='#e67e22', edgecolor='black')

plt.xticks(x_axis, models, rotation=45)
plt.xlabel("Models")
plt.ylabel("Percentage (%)")
plt.title("Comparison of Model Performance (Accuracy vs Recall)")
plt.legend()
plt.ylim(60, 100)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""# **_____________________________________________________________________________**

# End user interface
"""

import ipywidgets as widgets
from IPython.display import display

# Create widgets for user input
age_w = widgets.IntSlider(value=50, min=20, max=100, description='Age:')
sex_w = widgets.Dropdown(options=[('Male', 1), ('Female', 0)], description='Sex:')
cpt_w = widgets.Dropdown(options=[('ATA', 1), ('NAP', 2), ('ASY', 0), ('TA', 3)], description='Chest Pain:')
rbp_w = widgets.IntText(value=130, description='Resting BP:')
chol_w = widgets.IntText(value=200, description='Cholesterol:')
fbs_w = widgets.Dropdown(options=[('No', 0), ('Yes', 1)], description='Fasting BS > 120:')
mhr_w = widgets.IntText(value=150, description='Max HR:')
ea_w = widgets.Dropdown(options=[('No', 0), ('Yes', 1)], description='Exercise Angina:')
op_w = widgets.FloatText(value=0.0, description='Oldpeak:')
slope_w = widgets.Dropdown(options=[('Up', 2), ('Flat', 1), ('Down', 0)], description='ST Slope:')

predict_btn = widgets.Button(description='Predict with ALL Models', button_style='info', layout=widgets.Layout(width='50%'))
output = widgets.Output()

def get_all_predictions(b):
    with output:
        output.clear_output()

        # Prepare input array in the correct feature order
        raw_data = np.array([[age_w.value, cpt_w.value, rbp_w.value, chol_w.value,
                             fbs_w.value, mhr_w.value, op_w.value, slope_w.value,
                             sex_w.value, ea_w.value]])

        # Convert to DataFrame and apply the fitted MinMaxScaler
        input_df = pd.DataFrame(raw_data, columns=X.columns)
        scaled_input = scaler.transform(input_df)

        # Dictionary of our trained models
        trained_models = {
            'Logistic Regression': log_reg,
            'Linear SVM': svm_cv,
            'RBF SVC': svc_cv,
            'Decision Tree': dt_cv,
            'Random Forest': rf_cv,
            'Gradient Boosting': gb_cv,
            'KNN': knn_cv,
            'XGBoost': xgb_cv,
            'Naive Bayes': nb_cv,
            'Bagging': bag_cv
        }

        results = []
        for name, model in trained_models.items():
            pred = model.predict(scaled_input)[0]
            status = "⚠️ High Risk" if pred == 1 else "✅ Low Risk"
            results.append({'Model': name, 'Prediction': status})

        # Display results as a styled dataframe
        res_df = pd.DataFrame(results)
        display(res_df.style.set_properties(**{'text-align': 'center'}))

predict_btn.on_click(get_all_predictions)

# Layout Arrangement
left_box = widgets.VBox([age_w, sex_w, cpt_w, rbp_w, chol_w])
right_box = widgets.VBox([fbs_w, mhr_w, ea_w, op_w, slope_w])
ui = widgets.VBox([
    widgets.HTML("<h3>Enter Patient Clinical Data</h3>"),
    widgets.HBox([left_box, right_box]),
    predict_btn,
    output
])

display(ui)

# Input Widgets
age_w = widgets.IntSlider(value=54, min=20, max=100, description='Age:')
sex_w = widgets.Dropdown(options=[('Male', 1), ('Female', 0)], value=1, description='Sex:')
cpt_w = widgets.Dropdown(options=[('ASY', 0), ('ATA', 1), ('NAP', 2), ('TA', 3)], value=0, description='Chest Pain:')
rbp_w = widgets.IntText(value=130, description='Resting BP:')
chol_w = widgets.IntText(value=240, description='Cholesterol:')
fbs_w = widgets.Dropdown(options=[('No', 0), ('Yes', 1)], value=0, description='Fasting BS:')
mhr_w = widgets.IntText(value=150, description='Max HR:')
ea_w = widgets.Dropdown(options=[('No', 0), ('Yes', 1)], value=0, description='Ex. Angina:')
op_w = widgets.FloatText(value=1.0, description='Oldpeak:')
slope_w = widgets.Dropdown(options=[('Down', 0), ('Flat', 1), ('Up', 2)], value=1, description='ST Slope:')

predict_btn = widgets.Button(description='Run SVC Diagnostic', button_style='success', layout=widgets.Layout(width='300px'))
output = widgets.Output()

def run_diagnostic(b):
    with output:
        output.clear_output()
        # Features: Age, ChestPainType, RestingBP, Cholesterol, FastingBS, MaxHR, Oldpeak, ST_Slope, Sex_M, ExerciseAngina_Y
        input_data = pd.DataFrame([[age_w.value, cpt_w.value, rbp_w.value, chol_w.value, fbs_w.value,
                                   mhr_w.value, op_w.value, slope_w.value, sex_w.value, ea_w.value]],
                                 columns=X.columns)

        # Scale data using the fitted scaler
        scaled_data = scaler.transform(input_data)

        # Predict using the trained RBF SVC model
        prediction = svc_cv.predict(scaled_data)[0]

        # Visual Output
        result = "⚠️ High Risk of Heart Disease" if prediction == 1 else "✅ Low Risk of Heart Disease"
        color = "#e74c3c" if prediction == 1 else "#27ae60"

        display(widgets.HTML(f"<div style='border: 2px solid {color}; padding: 20px; border-radius: 8px; text-align: center;'>"
                             f"<h1 style='color: {color}; margin: 0;'>{result}</h1>"
                             f"<p style='margin-top: 10px;'>Model: Support Vector Classifier (RBF Kernel)</p></div>"))

predict_btn.on_click(run_diagnostic)

# Layout
left = widgets.VBox([age_w, sex_w, cpt_w, rbp_w, chol_w])
right = widgets.VBox([fbs_w, mhr_w, ea_w, op_w, slope_w])
ui = widgets.VBox([
    widgets.HTML("<h2>Patient Clinical Assessment (SVC)</h2>"),
    widgets.HBox([left, right]),
    widgets.Box([predict_btn], layout=widgets.Layout(justify_content='center', padding='20px')),
    output
])

display(ui)

"""# Export the model"""

import joblib
from google.colab import files


export_data = {
    'model': svc_cv,
    'scaler': scaler
}

joblib.dump(export_data, 'heart_disease_svc_model.pkl')
files.download('heart_disease_svc_model.pkl')